name: Create Zip Release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: archive release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: >
            *.git*
            *.psd
            /*designHelp/*
            /*psd/*
            /*assets/adventurebackpack/*
            /*assets/ae2fc/*
            /*assets/ae2stuff/*
            /*assets/alchemicalwizardry/*
            /*assets/architecturecraft/*
            /*assets/avaritia/*
            /*assets/avaritiaddons/*
            /*assets/backpack/*
            /*assets/battlegear2/*
            /*assets/baubles/*
            /*assets/beebetteratbees/*
            /*assets/betterp2p/*
            /*assets/botania/*
            /*assets/bq_standard/*
            /*assets/chisel/*
            /*assets/ironchest/*
            /*assets/mobsinfo/*
            /*assets/neiaddons/*
            /*assets/neiintegration/*
            /*assets/tcneiadditions/*
            /*assets/thaumcraft/*
