name: Create Zip Release
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@master
      - name: archive release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* *designHelp* *.psd'
